"""
Evidence for E-01 — the first concrete execution consumer.

Scope A — E-01 is a concrete realization of the `Agent` contract.
Scope B — it participates against a real, running Runtime.
Scope C — completion semantics (`spec` §13.3).
Scope D — residency: the region's boundary and dependency direction.
Scope E — the core is unaware of it; no reverse edge, no cycle.
"""

import ast
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from consumers import ReferenceAgent
from native_core.core.agent import Agent
from native_core.core.infrastructure import LocalAppendOnlyStorage, LocalExecutionSubstrate
from native_core.core.runtime import RuntimeState
from native_core.core.runtime.composition import create_runtime
from native_core.core.runtime.execution import create_execution_layer

REGION = Path(__file__).resolve().parent.parent
REPO = REGION.parent


def _running_runtime():
    storage = LocalAppendOnlyStorage(Path(tempfile.mkdtemp()))
    storage.provision()
    substrate = LocalExecutionSubstrate()
    substrate.provision()
    runtime = create_runtime(
        runtime_id="evidence-runtime", storage=storage, substrate=substrate
    )
    runtime.initialize()
    runtime.start()
    return runtime


def _module_imports(path):
    imported = set()
    for node in ast.walk(ast.parse(path.read_text())):
        if isinstance(node, ast.ImportFrom):
            imported.add(node.module or "")
        elif isinstance(node, ast.Import):
            imported |= {alias.name for alias in node.names}
    return imported


# --------------------------------------------------------------------------
# Scope A — a concrete realization
# --------------------------------------------------------------------------


class TestIsAConcreteConsumer(unittest.TestCase):
    def test_it_realizes_the_agent_contract(self):
        self.assertTrue(issubclass(ReferenceAgent, Agent))
        self.assertEqual(frozenset(), frozenset(ReferenceAgent.__abstractmethods__))

    def test_an_instance_is_an_agent(self):
        self.assertIsInstance(ReferenceAgent(), Agent)

    def test_it_implements_the_single_entry_point(self):
        self.assertIn("participate", vars(ReferenceAgent))

    def test_the_region_exports_it(self):
        import consumers

        self.assertEqual(["ReferenceAgent"], consumers.__all__)


# --------------------------------------------------------------------------
# Scope B — participation against a real Runtime
# --------------------------------------------------------------------------


class TestParticipatesAgainstARealRuntime(unittest.TestCase):
    def test_it_participates_in_a_bound_execution(self):
        runtime = _running_runtime()
        self.assertIs(RuntimeState.RUNNING, runtime.state)
        agent = ReferenceAgent()
        agent.participate(create_execution_layer(runtime))
        self.assertEqual((0,), agent.participated_sequences)

    def test_the_execution_ordinal_advances_across_participations(self):
        runtime = _running_runtime()
        agent = ReferenceAgent()
        for _ in range(3):
            agent.participate(create_execution_layer(runtime))
        self.assertEqual((0, 1, 2), agent.participated_sequences)

    def test_two_consumers_observe_the_runtime_issued_order(self):
        """The ordinal is issued by the Runtime, never generated by a consumer."""
        runtime = _running_runtime()
        first, second = ReferenceAgent(), ReferenceAgent()
        first.participate(create_execution_layer(runtime))
        second.participate(create_execution_layer(runtime))
        self.assertEqual((0,), first.participated_sequences)
        self.assertEqual((1,), second.participated_sequences)

    def test_it_reaches_the_boundary_the_core_boundary_could_not(self):
        """Residency outside the core is what makes inspection possible.

        Inside `native_core/core/agent/` the identifier constraint forbids
        naming the hosting Runtime, so an Execution could be received but never
        read."""
        runtime = _running_runtime()
        agent = ReferenceAgent()
        agent.participate(create_execution_layer(runtime))
        self.assertEqual(1, len(agent.participated_sequences))


# --------------------------------------------------------------------------
# Scope C — completion semantics (§13.3)
# --------------------------------------------------------------------------


class TestCompletionSemantics(unittest.TestCase):
    def test_participation_completes_by_returning_none(self):
        """Completion is the absence of rejection and failure; there is no
        success value, because no result model is ratified."""
        runtime = _running_runtime()
        self.assertIsNone(ReferenceAgent().participate(create_execution_layer(runtime)))

    def test_participation_raises_nothing_on_completion(self):
        runtime = _running_runtime()
        agent = ReferenceAgent()
        for _ in range(5):
            agent.participate(create_execution_layer(runtime))
        self.assertEqual(5, len(agent.participated_sequences))

    def test_it_declares_no_rejection_of_its_own_admission(self):
        """§4 — rejection is enforced upstream, not by the consumer."""
        source = (REGION / "reference_agent.py").read_text()
        tree = ast.parse(source)
        raises = [n for n in ast.walk(tree) if isinstance(n, ast.Raise)]
        self.assertEqual([], raises)

    def test_it_adds_no_precondition_check(self):
        """§17.2 — specifying preconditions does not authorize checking them."""
        tree = ast.parse((REGION / "reference_agent.py").read_text())
        participate = next(
            n
            for n in ast.walk(tree)
            if isinstance(n, ast.FunctionDef) and n.name == "participate"
        )
        self.assertEqual([], [n for n in ast.walk(participate) if isinstance(n, ast.If)])

    def test_the_observation_is_not_durable(self):
        """Trace is the only durable record; this is in-memory evidence only."""
        runtime = _running_runtime()
        agent = ReferenceAgent()
        agent.participate(create_execution_layer(runtime))
        self.assertEqual((), ReferenceAgent().participated_sequences)

    def test_the_record_is_immutable_to_callers(self):
        self.assertIsInstance(ReferenceAgent().participated_sequences, tuple)


# --------------------------------------------------------------------------
# Scope D — residency and dependency direction
# --------------------------------------------------------------------------


class TestResidency(unittest.TestCase):
    def test_it_lives_outside_the_native_core(self):
        self.assertNotIn("native_core", REGION.parts)
        self.assertEqual(REPO, REGION.parent)

    def test_it_depends_only_on_the_agent_contract(self):
        """C1 in spirit: one cross-boundary dependency, and it is the contract."""
        # `native_core.core.trace` and the sibling `observation` module joined
        # under `ACT-CC-R2A-IMPL-001 §31`: this consumer authors the Trace for
        # its own action. The cross-boundary count is still one contract plus
        # the Trace substrate it writes to — no Execution, no Runtime.
        self.assertEqual(
            {"__future__", "typing", "native_core.core.agent",
             "native_core.core.trace", "observation"},
            _module_imports(REGION / "reference_agent.py"),
        )

    def test_it_imports_no_execution_type(self):
        """C2 — the Execution layer is received, never imported.

        Checked by AST over imported *names*, not by substring: the module's
        docstring names these types precisely to explain that it does not import
        them, and a substring search reports that explanation as a violation."""
        imported_names = set()
        for node in ast.walk(ast.parse((REGION / "reference_agent.py").read_text())):
            if isinstance(node, ast.ImportFrom):
                imported_names |= {alias.name for alias in node.names}
            elif isinstance(node, ast.Import):
                imported_names |= {alias.name for alias in node.names}
        self.assertEqual(
            set(),
            imported_names
            & {"Execution", "ExecutionSession", "ExecutionContext", "create_execution_layer"},
        )
        self.assertEqual(
            {"Agent", "annotations", "List", "Tuple",
             "TraceWriter", "TracedAction", "runtime_identity"},
            imported_names,
        )

    def test_it_names_no_runtime_identifier(self):
        """C3 — honoured voluntarily; the region is not bound by it."""
        tree = ast.parse((REGION / "reference_agent.py").read_text())
        names = {n.id for n in ast.walk(tree) if isinstance(n, ast.Name)}
        names |= {n.attr for n in ast.walk(tree) if isinstance(n, ast.Attribute)}
        self.assertEqual(
            set(), names & {"Runtime", "AIOSRuntime", "runtime", "runtime_id"}
        )

    def test_the_region_depends_on_nothing_in_tools(self):
        for path in sorted(REGION.rglob("*.py")):
            for module in _module_imports(path):
                self.assertFalse(module.startswith("tools"), str(path))


# --------------------------------------------------------------------------
# Scope E — the core remains unaware
# --------------------------------------------------------------------------


class TestTheCoreRemainsUnaware(unittest.TestCase):
    def test_the_native_core_imports_nothing_from_consumers(self):
        """The reverse edge the region exists to prevent."""
        core = REPO / "native_core"
        for path in sorted(core.rglob("*.py")):
            for module in _module_imports(path):
                self.assertFalse(
                    module.startswith("consumers"), f"{path} imports consumers"
                )

    def test_tools_imports_nothing_from_consumers(self):
        for path in sorted((REPO / "tools").rglob("*.py")):
            for module in _module_imports(path):
                self.assertFalse(module.startswith("consumers"), str(path))

    def test_importing_the_core_does_not_load_the_region(self):
        program = (
            "import sys;"
            "import native_core.core.agent, native_core.core.runtime;"
            "print('CONSUMERS=' + repr([m for m in sys.modules if m.startswith('consumers')]))"
        )
        result = subprocess.run(
            [sys.executable, "-c", program], capture_output=True, text=True, cwd=str(REPO)
        )
        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("CONSUMERS=[]", result.stdout)


if __name__ == "__main__":
    unittest.main()
